# Project: Project1
# Makefile created by Embarcadero Dev-C++ 6.3

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = Main.o Algorithms.o "Binary\ Search\ Tree.o" "Binary\ Tree.o" Queues.o Stacks.o
LINKOBJ  = Main.o Algorithms.o "Binary Search Tree.o" "Binary Tree.o" Queues.o Stacks.o
LIBS     = -L"C:/Program Files (x86)/Embarcadero/Dev-Cpp/TDM-GCC-64/lib" -L"C:/Program Files (x86)/Embarcadero/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"C:/Program Files (x86)/Embarcadero/Dev-Cpp/TDM-GCC-64/include" -I"C:/Program Files (x86)/Embarcadero/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/include" -I"C:/Program Files (x86)/Embarcadero/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include"
CXXINCS  = -I"C:/Program Files (x86)/Embarcadero/Dev-Cpp/TDM-GCC-64/include" -I"C:/Program Files (x86)/Embarcadero/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/include" -I"C:/Program Files (x86)/Embarcadero/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include" -I"C:/Program Files (x86)/Embarcadero/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include/c++"
BIN      = dataStructsAndAlgo.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
DEL      = C:\Program Files (x86)\Embarcadero\Dev-Cpp\devcpp.exe INTERNAL_DEL

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${DEL} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

Main.o: Main.cpp
	$(CPP) -c Main.cpp -o Main.o $(CXXFLAGS)

Algorithms.o: Algorithms.cpp
	$(CPP) -c Algorithms.cpp -o Algorithms.o $(CXXFLAGS)

"Binary\ Search\ Tree.o": Binary\ Search\ Tree.cpp
	$(CPP) -c "Binary Search Tree.cpp" -o "Binary Search Tree.o" $(CXXFLAGS)

"Binary\ Tree.o": Binary\ Tree.cpp
	$(CPP) -c "Binary Tree.cpp" -o "Binary Tree.o" $(CXXFLAGS)

Queues.o: Queues.cpp
	$(CPP) -c Queues.cpp -o Queues.o $(CXXFLAGS)

Stacks.o: Stacks.cpp
	$(CPP) -c Stacks.cpp -o Stacks.o $(CXXFLAGS)
